server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kaban_users?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root@123
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  application:
    name: user-authentication-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    registerWithEureka: true


#    server.port=8085
#    spring.datasource.url=jdbc:mysql://localhost:3306/CustomerDb?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
#    spring.datasource.username=root
#    spring.datasource.password=root@123
#    spring.jpa.hibernate.ddl-auto=update
#    spring.jpa.show-sql=true
#    spring.datasource.driver-class-name= com.mysql.cj.jdbc.Driver
#    spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQL57Dialect
#    spring.application.name=user-authentication-service
#    eureka.client.serviceUrl.defaultZone= http://localhost:8761/eureka
#    eureka.client.fetchRegistry= true
#    eureka.client.registerWithEureka= true