FROM openjdk
WORKDIR usr/lib
ADD ./target/UserAutomotiveVehicleService-0.0.1-SNAPSHOT.jar /usr/lib/UserAutomotiveVehicleService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","UserAutomotiveVehicleService-0.0.1-SNAPSHOT.jar"]