server:
  port: 8081
spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/kanbanTaskData}
  application:
    name: user-kanban-board-service
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true

#  server.port=8081
#  spring.data.mongodb.database=customerProductDb
#  spring.data.mongodb.uri=mongodb://localhost:27017/
#  server.error.include-message=always